version: '3'

# Networks created to allow communication between containers
networks:
  books-network:
    driver: bridge

services:

  app:
    container_name: books_api
    build: .
    ports: 
      - 8080:8080 # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - db-postgres # Depends on postgres so we start that first
      # Other databases can be defined here
    networks:
      - books-network

  db-postgres:
    image: postgres:latest
    container_name: books_db
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - '5432:5432'
    volumes:
      - db_postgres:/var/lib/postgresql/data
    networks:
      - books-network

volumes:
  api:
  db_postgres: